version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: mflow-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: mflow-frontend
    ports:
      - "80:80"
    restart: always